import {readFile} from 'node:fs/promises';import {test,after} from 'node:test';import {initializeTestEnvironment,assertSucceeds,assertFails} from '@firebase/rules-unit-testing';import {doc,setDoc,getDoc,getDocs,collection,query,where,limit,updateDoc,deleteDoc,serverTimestamp,writeBatch} from 'firebase/firestore';
const env=await initializeTestEnvironment({projectId:'demo-foodfinder-security',firestore:{host:'127.0.0.1',port:8086,rules:await readFile(new URL('../firestore.rules',import.meta.url),'utf8')}});after(()=>env.cleanup());
const context=(uid,email=uid,extra={})=>env.authenticatedContext(uid,{email,email_verified:true,firebase:{sign_in_provider:'google.com'},auth_time:Math.floor(Date.now()/1000),...extra}).firestore();
const admin=context('owner','minmaung0307@gmail.com'),second=context('owner2','panna07@gmail.com'),user=context('visitor','visitor@example.com'),other=context('other','other@example.com'),anon=env.unauthenticatedContext().firestore();
const place=(status='draft')=>({name:'Test café',category:'cafe',cuisine:'coffee',city:'Yangon',country:'MM',cityId:'1298824',address:'Public address',phone:'',website:'',hours:'',description:'',status,lat:16.78,lon:96.15,hasImage:false,revision:1,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});
const note=uid=>({uid,type:'place',name:'Test suggestion',city:'Yangon',url:'',message:'A real test note for review.',status:'pending',createdAt:serverTimestamp(),updatedAt:serverTimestamp()});
test('both approved Google admins can write; anonymous public reads only published',async()=>{await assertSucceeds(getDoc(doc(admin,'ff_admin_access','check')));await assertFails(getDoc(doc(user,'ff_admin_access','check')));await assertSucceeds(setDoc(doc(admin,'ff_places','draft'),place()));await assertSucceeds(setDoc(doc(second,'ff_places','live'),place('published')));await assertSucceeds(getDoc(doc(anon,'ff_places','live')));await assertFails(getDoc(doc(anon,'ff_places','draft')));await assertSucceeds(getDocs(query(collection(anon,'ff_places'),where('status','==','published'),where('cityId','==','1298824'),limit(200))));await assertSucceeds(getDocs(query(collection(anon,'ff_places'),where('status','==','published'),where('cityId','in',['1298824','4474274','4474505']),limit(200))));await assertFails(getDocs(query(collection(anon,'ff_places'),limit(200))));await assertFails(getDocs(query(collection(anon,'ff_places'),where('status','==','published'),limit(201))));});
test('forged email, wrong provider, unverified account, stale sessions cannot write',async()=>{for(const db of [anon,user,context('x','minmaung0307@gmail.com',{email_verified:false}),context('x','minmaung0307@gmail.com',{firebase:{sign_in_provider:'password'}}),context('x','minmaung0307@gmail.com',{auth_time:Math.floor(Date.now()/1000)-1000})])await assertFails(setDoc(doc(db,'ff_places','attack'),place()));await assertFails(setDoc(doc(user,'roles','admin'),{admin:true}));});
test('schema and optimistic revisions enforced; archive hides public listing',async()=>{for(const patch of [{lat:91},{website:'javascript:alert(1)'},{extra:'injected'},{name:''},{category:'bad'},{revision:2},{description:'x'.repeat(2501)}])await assertFails(setDoc(doc(admin,'ff_places','invalid'),{...place(),...patch}));await assertFails(updateDoc(doc(admin,'ff_places','live'),{status:'archived',updatedAt:serverTimestamp()}));await assertSucceeds(updateDoc(doc(admin,'ff_places','live'),{status:'archived',revision:2,updatedAt:serverTimestamp()}));await assertFails(getDoc(doc(anon,'ff_places','live')));});
test('photo uploads bounded and drafts private; parent and image can be atomic',async()=>{const b=writeBatch(admin);b.set(doc(admin,'ff_places','photo'),{...place(),hasImage:true});b.set(doc(admin,'ff_media','photo'),{data:'data:image/webp;base64,UklGRg=='});await assertSucceeds(b.commit());await assertFails(getDoc(doc(anon,'ff_media','photo')));await assertSucceeds(updateDoc(doc(admin,'ff_places','photo'),{status:'published',revision:2,updatedAt:serverTimestamp()}));await assertSucceeds(getDoc(doc(anon,'ff_media','photo')));for(const data of ['data:image/svg+xml;base64,AAAA','data:image/webp;base64,'+'A'.repeat(160024)])await assertFails(setDoc(doc(admin,'ff_media','photo'),{data}));await assertFails(setDoc(doc(user,'ff_media','photo'),{data:'data:image/webp;base64,UklGRg=='}));});
test('private inbox ownership, pending cap, review and withdrawal',async()=>{await assertSucceeds(setDoc(doc(user,'ff_notes','visitor'),note('visitor')));await assertFails(getDoc(doc(other,'ff_notes','visitor')));await assertFails(getDocs(collection(user,'ff_notes')));await assertSucceeds(getDoc(doc(user,'ff_notes','visitor')));await assertSucceeds(getDocs(query(collection(admin,'ff_notes'),limit(100))));await assertFails(setDoc(doc(user,'ff_notes','visitor'),note('visitor')));await assertFails(setDoc(doc(user,'ff_notes','spoof'),note('spoof')));await assertFails(updateDoc(doc(user,'ff_notes','visitor'),{status:'reviewed',updatedAt:serverTimestamp()}));await assertSucceeds(updateDoc(doc(admin,'ff_notes','visitor'),{status:'reviewed',updatedAt:serverTimestamp()}));await assertSucceeds(setDoc(doc(user,'ff_notes','visitor'),note('visitor')));await assertSucceeds(deleteDoc(doc(user,'ff_notes','visitor')));await assertFails(setDoc(doc(anon,'ff_notes','anon'),note('anon')));});

test('optional menu fields preserve old records and reject unsafe or oversized content',async()=>{await assertSucceeds(setDoc(doc(admin,'ff_places','menu'),{...place('published'),dishesText:'Mohinga, mont ti',menuUrl:'https://example.com/menu'}));await assertSucceeds(getDoc(doc(anon,'ff_places','menu')));for(const patch of [{menuUrl:'javascript:alert(1)'},{dishesText:'x'.repeat(1501)}])await assertFails(setDoc(doc(admin,'ff_places','badmenu'),{...place(),...patch}));});
